@dominio = http://localhost:3000
@uid=67d2134192e8a897b6d1f3ed

### post de producto
POST {{dominio}}/api/v1/productos
Content-Type: application/json

{
    "name": "Dunes Anthrazite Black",
    "diseñador": "Jeaper K.Thomas",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

}

### update producto
PUT {{dominio}}/api/v1/productos/{{uid}}
Content-Type: application/json

{

}


### get all productos
GET {{dominio}}/api/v1/productos


